spring.application.name=sistema-sogra

# Conexão com o banco que criamos
spring.datasource.url=jdbc:mysql://localhost:3307/sistema_nutricao
spring.datasource.username=root
spring.datasource.password=

# Mostra o SQL no console (bom para aprender!)
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update